/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsciiArt: typeof import('./src/components/AsciiArt.vue')['default']
    ContactMarquee: typeof import('./src/components/ContactMarquee.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard.vue')['default']
    ContentMedia: typeof import('./src/components/ContentMedia.vue')['default']
    ContentSection: typeof import('./src/components/sections/ContentSection.vue')['default']
    ContentSplitter: typeof import('./src/components/ContentSplitter.vue')['default']
    ContentVideo: typeof import('./src/components/ContentVideo.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GalleryCard: typeof import('./src/components/GalleryCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeadingAnchor: typeof import('./src/components/HeadingAnchor.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    LocaleSwitcher: typeof import('./src/components/LocaleSwitcher.vue')['default']
    MediaLoadingIndicator: typeof import('./src/components/MediaLoadingIndicator.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NewsletterPreview: typeof import('./src/components/NewsletterPreview.vue')['default']
    OverviewSection: typeof import('./src/components/sections/OverviewSection.vue')['default']
    SectionCard: typeof import('./src/components/SectionCard.vue')['default']
    SkillsColumns: typeof import('./src/components/SkillsColumns.vue')['default']
    SkillsSection: typeof import('./src/components/sections/SkillsSection.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ToolsSection: typeof import('./src/components/sections/ToolsSection.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UCarousel: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UCollapsible: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Collapsible.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UMarquee: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Marquee.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageColumns: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/PageColumns.vue')['default']
    USeparator: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Separator.vue')['default']
    USplitter: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Splitter.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.11.2_7690ea3bae13a3803f58eb4a9451069c/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    VehiclePattern: typeof import('./src/components/VehiclePattern.vue')['default']
  }
}
